services:
  db:
    container_name: residentSys_pg
    image: postgres
    environment:
      POSTGRES_DB: residentSys
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - residentSys_network

volumes:
  postgres-data:
    driver: local

networks:
  residentSys_network:
    driver: bridge


